/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IThirdwebPrimarySale,
  IThirdwebPrimarySaleInterface,
} from "../IThirdwebPrimarySale";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "PrimarySaleRecipientUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "primarySaleRecipient",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_saleRecipient",
        type: "address",
      },
    ],
    name: "setPrimarySaleRecipient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IThirdwebPrimarySale__factory {
  static readonly abi = _abi;
  static createInterface(): IThirdwebPrimarySaleInterface {
    return new utils.Interface(_abi) as IThirdwebPrimarySaleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IThirdwebPrimarySale {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IThirdwebPrimarySale;
  }
}
